#!/bin/bash
# Taurine's test run. Same toolchain as the app: swiftc, nothing else.
#
# The whole app is compiled into the test binary (every source file except
# Sources/App/main.swift, whose top-level code would fight with the generated
# test entry point), so tests call production types directly with no seams,
# no mocks-by-protocol-gymnastics, and no second copy of anything.
#
# The entry point is generated rather than hand-maintained: every
# `func run<Something>Tests()` found in Tests/ is discovered and called, in
# alphabetical order. Adding a test file is therefore a one-file change.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=".build/tests"
BIN="$OUT/taurine-tests"
mkdir -p "$OUT"

# Discover the suites.
SUITES=$(grep -ho '^func run[A-Za-z0-9_]*Tests()' Tests/*.swift | sed 's/^func //; s/()$//' | sort -u)
if [ -z "$SUITES" ]; then
  echo "no test suites found in Tests/ (expected 'func run<Something>Tests()')" >&2
  exit 1
fi

GEN="$OUT/main.swift"
{
  echo "// Generated by tests/run.sh. Do not edit; do not commit."
  echo "import Foundation"
  echo
  for s in $SUITES; do echo "$s()"; done
  echo "exit(Check.report())"
} > "$GEN"

echo "▸ compiling tests ($(echo "$SUITES" | wc -l | tr -d ' ') suites)…"
SOURCES=()
while IFS= read -r f; do SOURCES+=("$f"); done < <(
  find Sources -name '*.swift' ! -path 'Sources/App/main.swift' | sort
)
while IFS= read -r f; do SOURCES+=("$f"); done < <(find Tests -name '*.swift' | sort)
SOURCES+=("$GEN")

swiftc -o "$BIN" "${SOURCES[@]}" \
  -framework Cocoa -framework IOKit -framework Carbon -framework ServiceManagement

echo "▸ running…"
"$BIN" "$@"
