#!/bin/bash
# Taurine's test run. Same toolchain as the app: swiftc, nothing else.
#
# The whole app is compiled into the test binary (every source file except
# Sources/App/main.swift, whose top-level code would fight with the generated
# test entry point), so tests call production types directly with no seams,
# no mocks-by-protocol-gymnastics, and no second copy of anything.
#
# The entry point is generated rather than hand-maintained: every
# `func run<Something>Tests()` found in Tests/ is discovered and called, in
# alphabetical order. Adding a test file is therefore a one-file change.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=".build/tests"
BIN="$OUT/taurine-tests"
mkdir -p "$OUT"

# The files that go in, gathered once. Discovery and compilation used to
# disagree about this list, one globbing Tests/ and the other walking it, so a
# suite in a subdirectory compiled, was never called, and the run went green
# with it silently missing. One list, used for both.
TESTS=()
while IFS= read -r f; do TESTS+=("$f"); done < <(find Tests -name '*.swift' | sort)

# Discover the suites. A declaration that spells the shape differently
# (`func  runXTests()`, a space before the parenthesis, an indented nested
# function) is a suite somebody meant to write and this would skip, so it is an
# error rather than a silence.
SUITES=$(grep -ho '^func run[A-Za-z0-9_]*Tests()' "${TESTS[@]}" | sed 's/^func //; s/()$//' | sort -u)
NEARLY=$(grep -hoE '^[[:space:]]*func[[:space:]]+run[A-Za-z0-9_]*Tests[[:space:]]*\(' "${TESTS[@]}" \
         | grep -vcE '^func run[A-Za-z0-9_]*Tests\($' || true)
if [ -z "$SUITES" ]; then
  echo "no test suites found in Tests/ (expected 'func run<Something>Tests()')" >&2
  exit 1
fi
if [ "${NEARLY:-0}" -gt 0 ]; then
  echo "$NEARLY test suite declaration(s) in Tests/ are spelled in a way this script cannot call." >&2
  echo "Write them as exactly: func run<Something>Tests()" >&2
  exit 1
fi

GEN="$OUT/main.swift"
{
  echo "// Generated by Tests/run.sh. Do not edit; do not commit."
  echo "import Foundation"
  echo
  for s in $SUITES; do echo "$s()"; done
  echo "exit(Check.report())"
} > "$GEN"

echo "▸ compiling tests ($(echo "$SUITES" | wc -l | tr -d ' ') suites)…"
SOURCES=()
while IFS= read -r f; do SOURCES+=("$f"); done < <(
  find Sources -name '*.swift' ! -path 'Sources/App/main.swift' | sort
)
SOURCES+=("${TESTS[@]}")
SOURCES+=("$GEN")

swiftc -o "$BIN" "${SOURCES[@]}" \
  -framework Cocoa -framework IOKit -framework Carbon -framework ServiceManagement

echo "▸ running…"
"$BIN" "$@"
